{
 "title": "Cosmos Validator",
 "description": "Stats of a Cosmos validator",
 "tags": [
  "cosmos",
  "blockchain",
  "validator"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cosmos_validator_tokens, chain_id)"
    }
   },
   {
    "name": "moniker",
    "label": "Moniker",
    "query": {
     "query": "label_values(cosmos_validator_tokens{chain_id=\"$chain_id\"}, moniker)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "rank",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(cosmos_validator_rank{chain_id=\"$chain_id\", moniker=\"$moniker\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "delegations count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"})",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "redelegations count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_redelegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) OR on() vector(0)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "unbondings count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(cosmos_validator_unbondings{chain_id=\"$chain_id\", moniker=\"$moniker\"}) OR on() vector(0)",
     "legendFormat": "{{ moniker }}"
    }
   ]
  },
  {
   "title": "total delegations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (denom)",
     "legendFormat": "{{ denom }}"
    }
   ]
  },
  {
   "title": "commission rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cosmos_validator_commission_rate{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "delegations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (moniker, denom)",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "delegations",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "cosmos_validator_delegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}"
    }
   ]
  },
  {
   "title": "redelegations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_validator_redelegations{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (moniker, denom)",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "redelegations",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "cosmos_validator_redelegations{chain_id=\"$chain_id\", moniker=\"$moniker\"} "
    }
   ]
  },
  {
   "title": "unbondings",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cosmos_validator_unbondings{chain_id=\"$chain_id\", moniker=\"$moniker\"}) by (moniker, denom)",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "unbondings",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "cosmos_validator_unbondings{chain_id=\"$chain_id\", moniker=\"$moniker\"} "
    }
   ]
  },
  {
   "title": "rewards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cosmos_validator_rewards{chain_id=\"$chain_id\", moniker=\"$moniker\"}",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "commission",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cosmos_validator_commission{chain_id=\"$chain_id\", moniker=\"$moniker\"}",
     "legendFormat": "{{ moniker }}, {{ denom }}"
    }
   ]
  },
  {
   "title": "missed blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "cosmos_validator_missed_blocks{chain_id=\"$chain_id\", moniker=\"$moniker\"}",
     "legendFormat": "{{ moniker }}"
    }
   ]
  }
 ]
}