name: test
on: [push]
jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v2
      - run: go version
      - run: go mod download
      - run: go build ./cmd/cosmos-exporter
      - run: go build ./cmd/kuji-cosmos-exporter
      - run: go build ./cmd/sei-cosmos-exporter
      - run: go build ./cmd/inj-cosmos-exporter
      - run: go build ./cmd/pryzm-cosmos-exporter
      - run: go build ./cmd/initia-cosmos-exporter
  go-vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-go@v2
      - run: go version
      - run: go mod download
      - run: go vet cmd/...
